# Generated by Django 2.2.7 on 2019-12-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20191203_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('user_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='User Name')),
                ('role', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), (None, 'Other')], default=None, max_length=30, null=True, verbose_name='Role')),
                ('street_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Street Name')),
                ('street_number', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Street Number')),
                ('apartment_number', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Apartment Number')),
                ('postal_code', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), (None, 'Other')], default=None, max_length=7, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Adress',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('user_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='User Name')),
                ('role', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), (None, 'Other')], default=None, max_length=30, null=True, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
    ]
