# Generated by Django 2.2.7 on 2019-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20191204_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Postal Code'),
        ),
    ]
