# Generated by Django 2.2.9 on 2020-01-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nazwisko')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True, verbose_name='Rok urodzenia')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
