# Generated by Django 2.2.9 on 2020-01-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Astronauta', 'verbose_name_plural': 'Astronauci'},
        ),
    ]
