# Generated by Django 2.2.8 on 2019-12-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=30, verbose_name='Role')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=30, verbose_name='Role')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('other', 'Other')], default='home', max_length=30, verbose_name='Role')),
                ('street', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='House Number')),
                ('apartment', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Apartment')),
                ('post_code', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Post Code')),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
